version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8001:8000"  # DynamoDB local escucha en 8000, expuesto como 8001 en host
    command: -jar DynamoDBLocal.jar -sharedDb
    networks:
      - backendnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"  # FastAPI
    depends_on:
      - dynamodb-local
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
      AWS_REGION: us-west-2
      AWS_ACCESS_KEY_ID: fakeMyKeyId
      AWS_SECRET_ACCESS_KEY: fakeSecretKey
    networks:
      - backendnet

networks:
  backendnet:
    driver: bridge
